### ISSUE TITLE
HTML and DHTML report does not include results for scenario outlines from SpecRun

### ISSUE THREAD

**Issue by AndyLPK247** [picklesdoc/pickles#551]
I followed all instructions here:
http://docs.picklesdoc.com/en/latest/IntegratingTestResultsFromSpecRun/

However, results are not posted for scenario outlines in the DHTML report:
![image](https://user-images.githubusercontent.com/17988946/46955304-9f215600-d060-11e8-95f2-8804c0c2387d.png)

Note that each value in the first column is unique.

**Comment by dirkrombauts** [comment]
Thanks for reporting this! Would it be possible for you to provide the Login feature file and the test result file? That would help me to debug.

Which version of Pickles are you using, and which test runner?

**Comment by AndyLPK247** [comment]
Pickles 2.19.0
SpecFlow 2.4.0
SpecRun.Runner 1.8.2

**Comment by dirkrombauts** [comment]
I will release version 2.20.1 soon. When I do, please try gain with that version. There are some relevant changes.

**Comment by AndyLPK247** [comment]
Okay, thanks! I'll wait and retry. If the problem persists, I'll share files. (I'll need to create an example project to reproduce the problem effectively.)

**Comment by dirkrombauts** [comment]
I released version [2.20.1](https://github.com/picklesdoc/pickles/releases/tag/v2.20.1), could you please try that version?

**Comment by AndyLPK247** [comment]
Thanks for the update, @dirkrombauts.

I attempted to use version 2.20.1, but the problem is not fully fixed. I made an example SpecFlow project with some passing and some failing tests:
![image](https://user-images.githubusercontent.com/17988946/47224612-f2a9e180-d389-11e8-927a-aa95b24b6616.png)

Here's the HTML report from the SpecRun report:
![image](https://user-images.githubusercontent.com/17988946/47224643-048b8480-d38a-11e8-90b5-7db3ea4cf6fc.png)

And here's the DHTML report:
![image](https://user-images.githubusercontent.com/17988946/47224702-1f5df900-d38a-11e8-8ae2-d8e0cfbabd7e.png)

**Comment by AndyLPK247** [comment]
Here's the feature file:

    Feature: Pickle

	Scenario: A
		Given A

	Scenario Outline: B
		Given some "<thing>"

		Examples: Things
			| thing |
			| 1     |
			| 2     |
			| 3     |

**Comment by AndyLPK247** [comment]
Here's the SpecRun report:
[PicklesTest_PicklesTest_2018-10-19T102505.zip](https://github.com/picklesdoc/pickles/files/2496248/PicklesTest_PicklesTest_2018-10-19T102505.zip)

**Comment by AndyLPK247** [comment]
Any update?

**Comment by dirkrombauts** [comment]
Sorry, not yet.

**Comment by dirkrombauts** [comment]
It's been an amazing time for me to work on Pickles. Now it's finally time for me to lay down the mantle and move on. I am leaving Pickles completely.

I am closing this issue, so that the next maintainer of this repository can start from a clean slate.

Do you want to take over active development and maintenance at Pickles? Contact me directly at dirk dot rombauts at picklesdoc dot com. I will hand over everything Pickles-related to you. This email address will remain active until 11 December 2020.
